### PR TITLE
Added in host, port, user input fields in options page

### PR DESCRIPTION
**Pull request by yousufdarr**
- Added in options page
image

- Added in `host`, `port`, `user` fields to options page
image

### CODE REVIEW

**Comment by odarr** [comment]
Great work!

**Comment by odarr** [comment]
Would it be possible to add some space between user input boxes and the save button?

**Comment by yousufdarr** [comment]
@odarr Sure here is the new version

image

**Comment by odarr** [comment]
Fixed bug with options contextual menu not showing up. Added the required "option_ui" section to manifest.json file.

**Pull request merged**
